version: '2'
services:
  app:
    image: auth1
    ports:
      - "8080:8080"
    depends_on:
      - mypostgres
  mypostgres:
    image: ekaterinach/postgrestest
    ports:
      - "5432:5432"
  client:
    image: ekaterinach/client
    ports:
      - "4200:80"
  mongodb:
    image: mongo
    ports:
      - "27017:27017"